language: generic



install: 
  # Get my folder
  - my_github=${PWD##*/}  
  - echo $my_github
  # shunit2
  - cd ..; git clone https://github.com/kward/shunit2.git; cd ${PWD##*/}

script: 
  - ./test
