language: generic



install: 
  # Get my folder
  - echo $PWD
  - my_github=${PWD##*/}  
  - echo $my_github
  # shunit2
  - cd ..; git clone https://github.com/kward/shunit2.git; cd travis_shunit2

script: 
  - ./test
